// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBODd73AR-IlBsYP5Jl0_p6wM5jDMLHVfs',
    appId: '1:745015994572:web:35caf3ca729e8076fbfa69',
    messagingSenderId: '745015994572',
    projectId: 'blacksheep-dff33',
    authDomain: 'blacksheep-dff33.firebaseapp.com',
    databaseURL: 'https://blacksheep-dff33-default-rtdb.firebaseio.com',
    storageBucket: 'blacksheep-dff33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_NOyp_xX6uN0bznNmsEHKGpu3kWivw9M',
    appId: '1:745015994572:android:fb946c5bc7a73a01fbfa69',
    messagingSenderId: '745015994572',
    projectId: 'blacksheep-dff33',
    databaseURL: 'https://blacksheep-dff33-default-rtdb.firebaseio.com',
    storageBucket: 'blacksheep-dff33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCugZa7wxJF8n3G5__SxFKYuA6Q9v-hIAQ',
    appId: '1:745015994572:ios:bdcfa7ee0705ba8afbfa69',
    messagingSenderId: '745015994572',
    projectId: 'blacksheep-dff33',
    databaseURL: 'https://blacksheep-dff33-default-rtdb.firebaseio.com',
    storageBucket: 'blacksheep-dff33.firebasestorage.app',
    iosBundleId: 'black.sheep.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCugZa7wxJF8n3G5__SxFKYuA6Q9v-hIAQ',
    appId: '1:745015994572:ios:bdcfa7ee0705ba8afbfa69',
    messagingSenderId: '745015994572',
    projectId: 'blacksheep-dff33',
    databaseURL: 'https://blacksheep-dff33-default-rtdb.firebaseio.com',
    storageBucket: 'blacksheep-dff33.firebasestorage.app',
    iosBundleId: 'black.sheep.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBODd73AR-IlBsYP5Jl0_p6wM5jDMLHVfs',
    appId: '1:745015994572:web:1f8a2931227d88d7fbfa69',
    messagingSenderId: '745015994572',
    projectId: 'blacksheep-dff33',
    authDomain: 'blacksheep-dff33.firebaseapp.com',
    databaseURL: 'https://blacksheep-dff33-default-rtdb.firebaseio.com',
    storageBucket: 'blacksheep-dff33.firebasestorage.app',
  );

}